# Generated by Django 4.2.8 on 2024-01-30 04:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Appname', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Student',
        ),
    ]
