# Generated by Django 4.2.8 on 2024-02-14 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Appname', '0002_delete_student'),
    ]

    operations = [
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=30, unique=True)),
                ('password', models.CharField(max_length=10)),
            ],
            options={
                'db_table': 'Orders',
            },
        ),
    ]
