# Generated by Django 4.2.8 on 2024-02-15 05:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Appname', '0003_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Admin',
            new_name='User',
        ),
        migrations.AlterModelTable(
            name='user',
            table='SignUp',
        ),
    ]
