# Generated by Django 4.2.8 on 2024-02-15 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Appname', '0004_rename_admin_user_alter_user_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=30, unique=True)),
                ('password', models.CharField(max_length=10)),
            ],
            options={
                'db_table': 'Login_Table',
            },
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
