# Generated by Django 4.2.8 on 2024-02-15 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Appname', '0005_admin_delete_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=30, unique=True)),
                ('email', models.CharField(default='', max_length=50, unique=True)),
                ('password', models.CharField(max_length=10)),
            ],
            options={
                'db_table': 'SignUp',
            },
        ),
    ]
