# Generated by Django 4.2.8 on 2024-02-29 04:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Appname', '0007_remove_user_email_remove_user_password_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
