# Generated by Django 4.2.8 on 2024-03-07 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Appname', '0008_delete_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='LoginTable',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=30, unique=True)),
                ('password', models.CharField(max_length=10)),
            ],
            options={
                'db_table': 'Login_Table',
            },
        ),
        migrations.DeleteModel(
            name='Admin',
        ),
    ]
