# Generated by Django 4.2.8 on 2024-02-15 05:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0003_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Admin',
        ),
    ]
