# Generated by Django 4.2.8 on 2024-02-29 04:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0005_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='admin',
            table='Ecommerce_admin_table',
        ),
    ]
