# Generated by Django 4.2.8 on 2024-03-07 06:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0006_alter_admin_table'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Admin',
        ),
    ]
